name: 'telegram-installonair-actions'
description: 'TypeScript GitHub Action for uploading files to InstallOnAir/LoadlyIO with Telegram notifications'
branding:
  color: 'green'
  icon: 'arrow-up-circle'

inputs:
  telegramToken:
    description: 'Telegram bot token for notifications'
    required: false
  telegramUid:
    description: 'Telegram chat ID for notifications'
    required: false
  messageTitle:
    description: 'Title for notifications'
    required: false
    default: 'App Build'
  installonairUserId:
    description: 'InstallOnAir user ID'
    required: false
    default: '74613'
  loadlyIoToken:
    description: 'LoadlyIO API token'
    required: false
  filePath:
    description: 'Path to the file to upload (APK/IPA)'
    required: true
  method:
    description: 'Action method: "send-only" | "installonair-build" | "loadlyio-build" | "all"'
    required: true
    default: 'installonair-build'
outputs:
  output:
    description: 'Upload result with status code and response data'
runs:
  using: 'node22'
  main: 'dist/index.js'
