name: 'telegram-installonair-actions'
description: 'Wait a designated number of milliseconds'
inputs:
  telegramToken:
    required: false
  telegramUid:
    required: false
  title:
      required: false
  message:
    required: false
  user_id:  # installonair user_id
    required: false
  fileForms: # installonair file
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
