name: 'telegram-installonair-actions'
description: 'Wait a designated number of milliseconds'
inputs:
  telegramToken:  # id of input
    required: false
  telegramUid:  # id of input
    required: false
  user_id:  # id of input
      required: false
  title:  # id of input
      required: false
  url:
    description: 'Web request URL endpoint'
    required: false
  method:
    description: 'Web request method (`GET`, `POST`, `PUT`, `PATCH`, `DELETE`)'
    required: true
    default: POST
  forms:
    description: Data to be transmitted,such as key, pwd, etc. Use json format
    required: false
  fileForms:
    description: Files to be transferred,such as 'file','image' etc. Use json format
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
